[package]
name = "project-tree-analyzer"
version = "1.0.0"
description = "Инструмент аудита структуры файлов"
authors = ["WAR100CK"]
license = "MIT"
repository = ""
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1.5", features = [ "window-start-dragging", "window-unminimize", "window-minimize", "window-hide", "window-close", "window-show", "dialog-all", "fs-write-file"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
